-- =============================================
-- 商户域 (Merchant Domain)
-- Tables: t_mch_info, t_mch_app, t_mch_notify
-- =============================================

CREATE TABLE t_mch_info (
    mch_no          VARCHAR(30)  NOT NULL,
    mch_name        VARCHAR(60)  NOT NULL,
    mch_short_name  VARCHAR(30),
    type            SMALLINT,
    state           SMALLINT     NOT NULL DEFAULT 1,
    agent_no        VARCHAR(30),
    contact_name    VARCHAR(30),
    contact_tel     VARCHAR(20),
    contact_email   VARCHAR(50),
    api_key         TEXT,
    remark          VARCHAR(256),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (mch_no)
);
CREATE INDEX idx_mch_info_agent ON t_mch_info (agent_no);
CREATE INDEX idx_mch_info_state ON t_mch_info (state);
CREATE TRIGGER trg_mch_info_updated_at BEFORE UPDATE ON t_mch_info FOR EACH ROW EXECUTE FUNCTION update_updated_at();

COMMENT ON TABLE  t_mch_info                IS '商户信息表';
COMMENT ON COLUMN t_mch_info.mch_no         IS '商户号';
COMMENT ON COLUMN t_mch_info.mch_name       IS '商户名称';
COMMENT ON COLUMN t_mch_info.mch_short_name IS '商户简称';
COMMENT ON COLUMN t_mch_info.type           IS '商户类型: 1-普通 2-个体 3-企业';
COMMENT ON COLUMN t_mch_info.state          IS '状态: 0-停用 1-正常';
COMMENT ON COLUMN t_mch_info.agent_no       IS '所属代理商号';
COMMENT ON COLUMN t_mch_info.api_key        IS 'API密钥';

CREATE TABLE t_mch_app (
    app_id          VARCHAR(30)  NOT NULL,
    mch_no          VARCHAR(30)  NOT NULL,
    app_name        VARCHAR(60),
    state           SMALLINT     NOT NULL DEFAULT 1,
    app_secret      TEXT,
    notify_url      VARCHAR(256),
    return_url      VARCHAR(256),
    remark          VARCHAR(256),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (app_id)
);
CREATE INDEX idx_mch_app_mch ON t_mch_app (mch_no);
CREATE TRIGGER trg_mch_app_updated_at BEFORE UPDATE ON t_mch_app FOR EACH ROW EXECUTE FUNCTION update_updated_at();

COMMENT ON TABLE  t_mch_app           IS '商户应用表';
COMMENT ON COLUMN t_mch_app.app_id    IS '应用ID';
COMMENT ON COLUMN t_mch_app.mch_no    IS '商户号';
COMMENT ON COLUMN t_mch_app.state     IS '状态: 0-停用 1-正常';

CREATE TABLE t_mch_notify (
    notify_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id           VARCHAR(30),
    order_type         VARCHAR(20),
    mch_no             VARCHAR(30),
    mch_order_no       VARCHAR(30),
    notify_url         VARCHAR(256),
    state              SMALLINT     NOT NULL DEFAULT 0,
    notify_count       INT          NOT NULL DEFAULT 0,
    notify_count_limit BIGINT       DEFAULT 6,
    last_notify_time   TIMESTAMP,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP             DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_mch_notify_order ON t_mch_notify (order_id);
CREATE INDEX idx_mch_notify_mch   ON t_mch_notify (mch_no);
CREATE INDEX idx_mch_notify_state ON t_mch_notify (state, created_at);
CREATE TRIGGER trg_mch_notify_updated_at BEFORE UPDATE ON t_mch_notify FOR EACH ROW EXECUTE FUNCTION update_updated_at();

COMMENT ON TABLE  t_mch_notify              IS '商户通知记录表';
COMMENT ON COLUMN t_mch_notify.state        IS '状态: 0-初始 1-通知中 2-成功 3-失败';
COMMENT ON COLUMN t_mch_notify.notify_count IS '已通知次数';
