-- =============================================
-- 支付通道域 (Payment Channel Domain)
-- =============================================

CREATE TABLE t_pay_way (
    way_code    VARCHAR(20)  NOT NULL PRIMARY KEY,
    way_name    VARCHAR(30)  NOT NULL,
    state       SMALLINT     NOT NULL DEFAULT 1,
    remark      VARCHAR(128),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP             DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER trg_pay_way_updated_at BEFORE UPDATE ON t_pay_way FOR EACH ROW EXECUTE FUNCTION update_updated_at();
COMMENT ON TABLE t_pay_way IS '支付方式定义表';

CREATE TABLE t_pay_passage (
    passage_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passage_name VARCHAR(60),
    if_code      VARCHAR(20),
    way_code     VARCHAR(20),
    fee_rate     BIGINT,
    fee_amount   BIGINT,
    state        SMALLINT     NOT NULL DEFAULT 1,
    remark       VARCHAR(256),
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP             DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_passage_state ON t_pay_passage (state);
CREATE TRIGGER trg_pay_passage_updated_at BEFORE UPDATE ON t_pay_passage FOR EACH ROW EXECUTE FUNCTION update_updated_at();
COMMENT ON TABLE t_pay_passage IS '支付通道表';

CREATE TABLE t_pay_interface_define (
    if_code          VARCHAR(20)  NOT NULL PRIMARY KEY,
    if_name          VARCHAR(60)  NOT NULL,
    if_type          SMALLINT,
    config_page_type VARCHAR(20),
    icon             VARCHAR(128),
    bg_color         VARCHAR(20),
    state            SMALLINT     NOT NULL DEFAULT 1,
    remark           VARCHAR(256),
    config_info      TEXT,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP             DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER trg_pay_if_define_updated_at BEFORE UPDATE ON t_pay_interface_define FOR EACH ROW EXECUTE FUNCTION update_updated_at();
COMMENT ON TABLE  t_pay_interface_define IS '支付接口定义表';
COMMENT ON COLUMN t_pay_interface_define.config_info IS '配置定义(JSON): 支付参数字段定义';

CREATE TABLE t_pay_interface_config (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    info_type VARCHAR(20)  NOT NULL,
    info_id   VARCHAR(64)  NOT NULL,
    if_code   VARCHAR(20)  NOT NULL,
    if_params TEXT,
    state     SMALLINT     NOT NULL DEFAULT 1,
    remark    VARCHAR(256),
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP            DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (info_type, info_id, if_code)
);
CREATE TRIGGER trg_pay_if_config_updated_at BEFORE UPDATE ON t_pay_interface_config FOR EACH ROW EXECUTE FUNCTION update_updated_at();
COMMENT ON TABLE t_pay_interface_config IS '支付接口配置表';

CREATE TABLE t_mch_pay_passage (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mch_no     VARCHAR(30)  NOT NULL,
    app_id     VARCHAR(30)  NOT NULL,
    way_code   VARCHAR(20)  NOT NULL,
    passage_id BIGINT,
    fee_rate   BIGINT,
    fee_amount BIGINT,
    state      SMALLINT     NOT NULL DEFAULT 1,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP             DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_mch_passage ON t_mch_pay_passage (mch_no, app_id, way_code);
CREATE TRIGGER trg_mch_pay_passage_updated_at BEFORE UPDATE ON t_mch_pay_passage FOR EACH ROW EXECUTE FUNCTION update_updated_at();
COMMENT ON TABLE t_mch_pay_passage IS '商户支付通道关联表';
