-- =============================================
-- 代理商域 (Agent Domain)
-- =============================================

CREATE TABLE t_agent_info (
    agent_no        VARCHAR(30)  NOT NULL PRIMARY KEY,
    agent_name      VARCHAR(60)  NOT NULL,
    level           SMALLINT,
    parent_agent_no VARCHAR(30),
    profit_rate     NUMERIC(10,4),
    state           SMALLINT     NOT NULL DEFAULT 1,
    contact_name    VARCHAR(30),
    contact_tel     VARCHAR(20),
    contact_email   VARCHAR(50),
    remark          VARCHAR(256),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP             DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_agent_parent ON t_agent_info (parent_agent_no);
CREATE INDEX idx_agent_state  ON t_agent_info (state);
CREATE TRIGGER trg_agent_info_updated_at BEFORE UPDATE ON t_agent_info FOR EACH ROW EXECUTE FUNCTION update_updated_at();

COMMENT ON TABLE  t_agent_info             IS '代理商信息表';
COMMENT ON COLUMN t_agent_info.level       IS '代理等级: 1-一级 2-二级';
COMMENT ON COLUMN t_agent_info.profit_rate IS '分润比例';

CREATE TABLE t_agent_account (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_no      VARCHAR(30)  NOT NULL UNIQUE,
    balance       BIGINT       NOT NULL DEFAULT 0,
    frozen_amount BIGINT       NOT NULL DEFAULT 0,
    settled_amount BIGINT      NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP             DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER trg_agent_account_updated_at BEFORE UPDATE ON t_agent_account FOR EACH ROW EXECUTE FUNCTION update_updated_at();

COMMENT ON TABLE  t_agent_account         IS '代理商账户表';
COMMENT ON COLUMN t_agent_account.balance IS '可用余额(分)';
