-- =============================================
-- 账户与结算域 (Account & Settlement Domain)
-- =============================================

CREATE TABLE t_account_balance (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_no       VARCHAR(30)  NOT NULL UNIQUE,
    account_name     VARCHAR(60),
    account_type     SMALLINT,
    balance          BIGINT       NOT NULL DEFAULT 0,
    frozen_amount    BIGINT       NOT NULL DEFAULT 0,
    unsettled_amount BIGINT       NOT NULL DEFAULT 0,
    settled_amount   BIGINT       NOT NULL DEFAULT 0,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP             DEFAULT CURRENT_TIMESTAMP
);
CREATE TRIGGER trg_account_balance_updated_at BEFORE UPDATE ON t_account_balance FOR EACH ROW EXECUTE FUNCTION update_updated_at();
COMMENT ON TABLE t_account_balance IS '账户余额表';

CREATE TABLE t_account_history (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_no     VARCHAR(30)  NOT NULL,
    change_type    SMALLINT     NOT NULL,
    change_amount  BIGINT       NOT NULL,
    balance_before BIGINT       NOT NULL,
    balance_after  BIGINT       NOT NULL,
    biz_order_no   VARCHAR(30),
    biz_type       VARCHAR(20),
    remark         VARCHAR(256),
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP             DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_acct_history_time ON t_account_history (account_no, created_at);
CREATE TRIGGER trg_account_history_updated_at BEFORE UPDATE ON t_account_history FOR EACH ROW EXECUTE FUNCTION update_updated_at();
COMMENT ON TABLE  t_account_history             IS '账户变动流水表';
COMMENT ON COLUMN t_account_history.change_type IS '变动类型: 1-收入 2-支出 3-冻结 4-解冻 5-结算';

CREATE TABLE t_sett_record (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sett_no           VARCHAR(30)  NOT NULL UNIQUE,
    account_no        VARCHAR(30),
    mch_no            VARCHAR(30),
    agent_no          VARCHAR(30),
    sett_amount       BIGINT       NOT NULL,
    fee_amount        BIGINT       NOT NULL DEFAULT 0,
    remit_amount      BIGINT,
    state             SMALLINT     NOT NULL DEFAULT 0,
    bank_account_no   VARCHAR(30),
    bank_account_name VARCHAR(60),
    bank_name         VARCHAR(60),
    err_msg           VARCHAR(256),
    success_time      TIMESTAMP,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP             DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_sett_mch ON t_sett_record (mch_no, state);
CREATE TRIGGER trg_sett_record_updated_at BEFORE UPDATE ON t_sett_record FOR EACH ROW EXECUTE FUNCTION update_updated_at();
COMMENT ON TABLE  t_sett_record       IS '结算记录表';
COMMENT ON COLUMN t_sett_record.state IS '0-初始 1-结算中 2-成功 3-失败';

CREATE TABLE t_sett_bank_account (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_no        VARCHAR(30)  NOT NULL,
    mch_no            VARCHAR(30),
    bank_name         VARCHAR(60),
    bank_branch       VARCHAR(100),
    bank_account_no   VARCHAR(30),
    bank_account_name VARCHAR(60),
    account_type      SMALLINT,
    state             SMALLINT     NOT NULL DEFAULT 1,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP             DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_bank_acct ON t_sett_bank_account (account_no);
CREATE TRIGGER trg_sett_bank_account_updated_at BEFORE UPDATE ON t_sett_bank_account FOR EACH ROW EXECUTE FUNCTION update_updated_at();
COMMENT ON TABLE t_sett_bank_account IS '结算银行账户表';
