-- =============================================
-- 系统管理域 - 用户与权限 (System - User & RBAC)
-- =============================================

CREATE TABLE t_sys_user (
    sys_user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_username VARCHAR(30)  NOT NULL,
    login_password VARCHAR(128) NOT NULL,
    realname       VARCHAR(30),
    telphone       VARCHAR(20),
    sex            SMALLINT,
    avatar_url     VARCHAR(256),
    user_type      SMALLINT     NOT NULL,
    belong_id      VARCHAR(30),
    state          SMALLINT     NOT NULL DEFAULT 1,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP             DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (login_username, user_type)
);
CREATE INDEX idx_user_belong ON t_sys_user (user_type, belong_id);
CREATE TRIGGER trg_sys_user_updated_at BEFORE UPDATE ON t_sys_user FOR EACH ROW EXECUTE FUNCTION update_updated_at();
COMMENT ON TABLE  t_sys_user           IS '系统用户表';
COMMENT ON COLUMN t_sys_user.user_type IS '用户类型: 1-运营 2-商户 3-代理商';

CREATE TABLE t_sys_role (
    role_id     VARCHAR(30) NOT NULL PRIMARY KEY,
    role_name   VARCHAR(30) NOT NULL,
    belong_type VARCHAR(20),
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP            DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_role_belong ON t_sys_role (belong_type);
CREATE TRIGGER trg_sys_role_updated_at BEFORE UPDATE ON t_sys_role FOR EACH ROW EXECUTE FUNCTION update_updated_at();
COMMENT ON TABLE t_sys_role IS '系统角色表';

CREATE TABLE t_sys_entitlement (
    ent_id    VARCHAR(30)  NOT NULL PRIMARY KEY,
    ent_name  VARCHAR(60)  NOT NULL,
    ent_type  SMALLINT     NOT NULL,
    menu_icon VARCHAR(60),
    menu_uri  VARCHAR(128),
    parent_id VARCHAR(30),
    ent_sort  INT          NOT NULL DEFAULT 0,
    state     SMALLINT     NOT NULL DEFAULT 1,
    sys_type  VARCHAR(20),
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP            DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_ent_sys ON t_sys_entitlement (sys_type, ent_type);
CREATE TRIGGER trg_sys_ent_updated_at BEFORE UPDATE ON t_sys_entitlement FOR EACH ROW EXECUTE FUNCTION update_updated_at();
COMMENT ON TABLE  t_sys_entitlement          IS '系统权限表';
COMMENT ON COLUMN t_sys_entitlement.ent_type IS '1-菜单 2-按钮';

CREATE TABLE t_sys_user_role (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sys_user_id BIGINT      NOT NULL,
    role_id     VARCHAR(30) NOT NULL,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP            DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_user_role_user ON t_sys_user_role (sys_user_id);
CREATE INDEX idx_user_role_role ON t_sys_user_role (role_id);
CREATE TRIGGER trg_sys_user_role_updated_at BEFORE UPDATE ON t_sys_user_role FOR EACH ROW EXECUTE FUNCTION update_updated_at();
COMMENT ON TABLE t_sys_user_role IS '用户角色关联表';

CREATE TABLE t_sys_role_entitlement (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id    VARCHAR(30) NOT NULL,
    ent_id     VARCHAR(30) NOT NULL,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP            DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_role_ent_role ON t_sys_role_entitlement (role_id);
CREATE INDEX idx_role_ent_ent  ON t_sys_role_entitlement (ent_id);
CREATE TRIGGER trg_sys_role_ent_updated_at BEFORE UPDATE ON t_sys_role_entitlement FOR EACH ROW EXECUTE FUNCTION update_updated_at();
COMMENT ON TABLE t_sys_role_entitlement IS '角色权限关联表';
