-- =============================================
-- 系统管理域 - 配置与日志 (System - Config & Log)
-- =============================================

CREATE TABLE t_sys_config (
    config_key   VARCHAR(60)  NOT NULL PRIMARY KEY,
    config_name  VARCHAR(60),
    config_value TEXT,
    config_group VARCHAR(30),
    remark       VARCHAR(256),
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP             DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_config_group ON t_sys_config (config_group);
CREATE TRIGGER trg_sys_config_updated_at BEFORE UPDATE ON t_sys_config FOR EACH ROW EXECUTE FUNCTION update_updated_at();
COMMENT ON TABLE  t_sys_config              IS '系统配置表';
COMMENT ON COLUMN t_sys_config.config_group IS '分组: system/settlement/notify/order';

CREATE TABLE t_sys_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_type     SMALLINT,
    user_id       VARCHAR(30),
    user_name     VARCHAR(30),
    sys_type      VARCHAR(20),
    method_name   VARCHAR(128),
    method_remark VARCHAR(128),
    req_url       VARCHAR(256),
    opt_req_param TEXT,
    opt_res_info  TEXT,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP          DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_log_sys  ON t_sys_log (sys_type, created_at);
CREATE INDEX idx_log_user ON t_sys_log (sys_type, user_id);
CREATE TRIGGER trg_sys_log_updated_at BEFORE UPDATE ON t_sys_log FOR EACH ROW EXECUTE FUNCTION update_updated_at();
COMMENT ON TABLE t_sys_log IS '系统操作日志表';
